# Change these first
owner: indykite # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: IndyKite.ID Console
    url: https://console.indykite.id
    icon: https://console.indykite.id/favicon.png
    maxResponseTime: 5000
  - name: IndyKite.ME
    url: https://indykite.me
    icon: https://indykite.me/favicon.png
    maxResponseTime: 5000
  - name: Jarvis Platform API
    url: $JARVIS_PLATFORM_URL
    icon: https://console.indykite.id/favicon.png
    maxResponseTime: 5000
  - name: IndyKite Community Web
    url: https://indykite.one/favicon.png
    icon: https://storage.googleapis.com/buildtoriot-prod-cdn/darkLogo--ecd2e1a8-e2bc-4397-bf13-a29065634323--zeybxg?1628600699933
    maxResponseTime: 5000

assingees:
  - maprokes
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.indykite.com
  themeUrl: https://status.indykite.com/style.css
  logoUrl: https://avatars.githubusercontent.com/u/66381419?s=60&v=4
  theme: dark
  name: IndyKite Status Page
  introTitle: "Having trouble? Check out [documentation](https://indykite.one/blog?category=57ddfc6c-a7f5-4269-8afc-6d023e32e7bc) or email us at support@indykite.com."
  favicon: https://console.indykite.id/favicon.png
  metaTags:
    - name: "color-scheme"
      content: "dark"
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: IndyKite
      href: https://indykite.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
